<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Invoice extends Seeder
{
    public function run()
    {
        $data = [
            'statement_number'  => '09123123',
            'issue_date'  => date('d M Y'),
            'due_date'  => date('d M Y'),
            'issue_to' => "John Doe" ,
            'currency' => '$',
            'items' => 'TV',
            'tax_shipping_amount' => '1000',
            'amount' => '123',
            'remarks' => 'Generated by seed',
            'template' => '?',
        ];

        $this->db->table('invoices')->insert($data);
    }
}
